# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
    -   id: ruff-check
    -   id: ruff-format

-   repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.5
    hooks:
    -   id: rstcheck
        files: ^README\.rst$
